import React from "react";
import { useForm } from "react-hook-form";
import { useDispatch } from "react-redux";
import { addVendor } from "./vendorSlice";
import axios from 'axios'

export const VendorForm = () => {
    const dispatch = useDispatch()

    const onSubmit = (data) => {
        axios
            // Save new vendor
            .post('http://localhost:3001/api/vendor/insert', {
                name: data.vendorName
            })
            // Add new vendor to state, *** with the insertId generated by MySQL ***
            .then(response => {
                console.log(response.data.insertId)
                const newVendor = {
                    id: response.data.insertId,
                    name: data.vendorName
                }
                dispatch(addVendor(newVendor))
            })
            .catch(error => console.log(error))
    }

    const { register, handleSubmit, formState: { errors } } = useForm();
    return (

        <>
            <form onSubmit={handleSubmit(onSubmit)}>
                <div>
                    <label>Vendor Name:</label>
                    <input {...register("vendorName", { required: true })} />
                    {errors.exampleRequired && <span>This field is required</span>}
                </div>
                <input type="submit" />
            </form>
        </>


    );
}